title: icus.data
email: alan@ttcrossroads.net
# url: "https://kijinosu.github.io/icus.data/"
# baseurl: "docs"
description: An R data package for researching the International Conferences on the Unity of Science
# theme: jekyll-theme-minimal
theme: minima
# navbar:
#   - title: Search Examples
#     path: /search-examples.md